# You don't need to modify the following 
FROM mongo:4.4

WORKDIR /var/dmongo
# copy initial data file to a directory in mongodb container
_________________________

# run mongoimport
_________________________
